/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package frontend;

import Shapes.Shape;
import java.awt.Graphics;
import java.util.ArrayList;
/**
 *
 * @author DELL
 */
public class DrawingEngine extends javax.swing.JPanel implements Drawing {
    
    ArrayList<Shape> shapes = new ArrayList<>();

    /**
     * Creates new form jpanel
     */
    public DrawingEngine() {
        initComponents();
    }


    @Override
    public void addShape(Shape shape) {
        shapes.add(shape);
        repaint();
    }

    @Override
    public void removeShape(Shape shape) {
        shapes.remove(shape);
        repaint(); 
    }

    @Override
    public Shape[] getShapes() {
        return shapes.toArray(Shape[]::new);
    }

    @Override
    public void refresh(Graphics canvas) {
        super.paintComponent(canvas);
        for (Shape shape : shapes) {
            shape.draw(canvas);
        }
    }

   
    @Override
    protected void paintComponent(Graphics g) {
        super.paintComponent(g);
        refresh(g);  
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
